In [13]:
import cv2


# Получение всех возможных флагов для преобразования цветов
flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
print(flags)

['COLOR_BAYER_BG2BGR', 'COLOR_BAYER_BG2BGRA', 'COLOR_BAYER_BG2BGR_EA', 'COLOR_BAYER_BG2BGR_VNG', 'COLOR_BAYER_BG2GRAY', 'COLOR_BAYER_BG2RGB', 'COLOR_BAYER_BG2RGBA', 'COLOR_BAYER_BG2RGB_EA', 'COLOR_BAYER_BG2RGB_VNG', 'COLOR_BAYER_BGGR2BGR', 'COLOR_BAYER_BGGR2BGRA', 'COLOR_BAYER_BGGR2BGR_EA', 'COLOR_BAYER_BGGR2BGR_VNG', 'COLOR_BAYER_BGGR2GRAY', 'COLOR_BAYER_BGGR2RGB', 'COLOR_BAYER_BGGR2RGBA', 'COLOR_BAYER_BGGR2RGB_EA', 'COLOR_BAYER_BGGR2RGB_VNG', 'COLOR_BAYER_GB2BGR', 'COLOR_BAYER_GB2BGRA', 'COLOR_BAYER_GB2BGR_EA', 'COLOR_BAYER_GB2BGR_VNG', 'COLOR_BAYER_GB2GRAY', 'COLOR_BAYER_GB2RGB', 'COLOR_BAYER_GB2RGBA', 'COLOR_BAYER_GB2RGB_EA', 'COLOR_BAYER_GB2RGB_VNG', 'COLOR_BAYER_GBRG2BGR', 'COLOR_BAYER_GBRG2BGRA', 'COLOR_BAYER_GBRG2BGR_EA', 'COLOR_BAYER_GBRG2BGR_VNG', 'COLOR_BAYER_GBRG2GRAY', 'COLOR_BAYER_GBRG2RGB', 'COLOR_BAYER_GBRG2RGBA', 'COLOR_BAYER_GBRG2RGB_EA', 'COLOR_BAYER_GBRG2RGB_VNG', 'COLOR_BAYER_GR2BGR', 'COLOR_BAYER_GR2BGRA', 'COLOR_BAYER_GR2BGR_EA', 'COLOR_BAYER_GR2BGR_VNG', 'COLOR_

In [14]:
# Разложение исходного изображения на каналы HSV
pic = 'test_picture.jpg'
image = cv2.imread(pic)

# Конвертация в HSV
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv)

cv2.imshow('image',image)
cv2.imshow('h', h)
cv2.imshow('s', s)
cv2.imshow('v', v)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
import numpy as np


green = np.uint8([[[0, 255, 0]]])
hsv_green = cv2.cvtColor(green, cv2.COLOR_BGR2HSV)
print(hsv_green)

[[[ 60 255 255]]]


In [16]:
lower_blue, upper_blue = np.array([28, 50, 10]), np.array([45, 255, 255])

# Порогвая обработка изображения для получения только голубых оттенков
mask = cv2.inRange(hsv, lower_blue, upper_blue)

# Применение битовых операций к исходному изображению
result = cv2.bitwise_and(image, image, mask=mask)
cv2.imshow('image', image)
cv2.imshow('mask', mask)
cv2.imshow('result', result)

lower_blue, upper_blue = np.array([27, 0, 0]), np.array([50, 255, 255])
mask = cv2.inRange(hsv, lower_blue, upper_blue)
result2 = cv2.bitwise_and(image, image, mask=mask)

cv2.imshow('result2', result2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
gray_image = cv2.imread(pic, 0)
# Разные варианты пороговой обработки
ret,thresh1 = cv2.threshold(gray_image,127,255,cv2.THRESH_BINARY)
ret,thresh2 = cv2.threshold(gray_image,127,255,cv2.THRESH_BINARY_INV)
ret,thresh3 = cv2.threshold(gray_image,127,255,cv2.THRESH_TRUNC)
ret,thresh4 = cv2.threshold(gray_image,127,255,cv2.THRESH_TOZERO)
ret,thresh5 = cv2.threshold(gray_image,127,255,cv2.THRESH_TOZERO_INV)

cv2.imshow('gray_image',gray_image)
cv2.imshow('thresh1',thresh1)
cv2.imshow('thresh2',thresh2)
cv2.imshow('thresh3',thresh3)
cv2.imshow('thresh4',thresh4)
cv2.imshow('thresh5',thresh5)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
cv2.imshow('image', gray_image)
ret, th1 = cv2.threshold(
    gray_image,
    127,
    255,
    cv2.THRESH_BINARY
)

th2 = cv2.adaptiveThreshold(
    gray_image,
    255,
    cv2.ADAPTIVE_THRESH_MEAN_C,
    cv2.THRESH_BINARY,
    11,
    2
)

th3 = cv2.adaptiveThreshold(
    gray_image,
    255,
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY,
    11,
    2
)

cv2.imshow('thresh1',th1)
cv2.imshow('thresh2',th2)
cv2.imshow('thresh3',th3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
cv2.imshow('image', gray_image)
# Пороговая обработка с использованием Оцу
ret, th1 = cv2.threshold(
    gray_image,
    127,
    255,
    cv2.THRESH_BINARY
)
ret, th2 = cv2.threshold(
    gray_image,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)
# Обработка Оцу после применения фильтра Гаусса
blur = cv2.GaussianBlur(
    gray_image,
    (5, 5),
    0
)
ret, th3 = cv2.threshold(
    gray_image,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

cv2.imshow('thresh1',th1)
cv2.imshow('thresh2',th2)
cv2.imshow('thresh3',th3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
# Получение информации об изображении и изменение его размеров
height, width = image.shape[:2]
result = cv2.resize(image, (2 * width, 2 * height), interpolation=cv2.INTER_CUBIC)

cv2.imshow('result', result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
# Задаем матрицу преобразования для смещения изображения
M = np.float32([[1, 0, 100], [0, 1, 50]])
dst = cv2.warpAffine(image, M, (width, height))

cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
# Вращение изображения
M = cv2.getRotationMatrix2D((width / 2, height / 2), 37, 1)
dst = cv2.warpAffine(image, M, (width, height))

cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
# Аффинное преобразование
pts1 = np.float32([[50, 50], [200,50], [50, 200]])
pts2 = np.float32([[10, 100], [200, 50], [100, 250]])

M = cv2.getAffineTransform(pts1, pts2)
dst = cv2.warpAffine(image, M, (width, height))

cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
# Перспективное преобразование
pts1 = np.float32([[27, 34], [182, 27],[ 13, 190], [191, 191]])
pts2 = np.float32([[0, 0], [300, 0], [0, 300], [300, 300]])

M = cv2.getPerspectiveTransform(pts1, pts2)

dst = cv2.warpPerspective(image, M, (300, 300))

cv2.imshow('image', image)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
# Сглаживание изображения
kernel = np.ones((5, 5), np.float32) / 25
dst = cv2.filter2D(image, -1, kernel)

cv2.imshow('image', image)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
# Различные варианты размытия изображений
blur = cv2.blur(image, (5, 5))
gaus = cv2.GaussianBlur(image, (5, 5), 0)
medi = cv2.medianBlur(image, 5)
bila = cv2.bilateralFilter(image, 9, 75, 75)

cv2.imshow('image', image)
cv2.imshow('blur', blur)
cv2.imshow('gaus', gaus)
cv2.imshow('medi', medi)
cv2.imshow('bila', bila)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
from captcha.image import ImageCaptcha


# Создание картинки с текстом
text = ImageCaptcha(60, 60)
# Структура возвращаемого списка: [filename, label, (width, height)]
text.write('j', 'j.png')

# Морфологические обработки
img = cv2.imread('j.png', 0)
kernel = np.ones((3, 3), np.uint8)

erosion = cv2.erode(img, kernel, iterations=1)
dilation = cv2.dilate(img, kernel, iterations=1)
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

cv2.imshow('img', img)
cv2.imshow('erosion', erosion)
cv2.imshow('dilation', dilation)
cv2.imshow('opening', opening)
cv2.imshow('closing', closing)
cv2.imshow('gradient', gradient)
cv2.imshow('tophat', tophat)
cv2.imshow('blackhat', blackhat)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
# Пользовательские структурирующие элементы
# Rectangular Kernel
cv2.getStructuringElement(cv2.MORPH_RECT, (5, 5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [33]:
# Elliptical Kernel
cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [34]:
# Cross-shaped Kernel
cv2.getStructuringElement(cv2.MORPH_CROSS, (5, 5))

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]], dtype=uint8)