# <p align='center'>Лабораторная работа №2</p>
## <p align='center'>Базовые операции с изображениями</p>

<p align='right'>Выполнил: студент гр. 5.306М Лаптев А.В.</p>


# Основные операции с изображениями
## Pixel-значение
Для работы с частью изображения можно получать доступ к конкретным пикселям на изображении и изменять их. Пример подобной работы с изображением можно увидеть ниже:

In [1]:
import cv2


pic = '../resources/test_picture.jpg'
image = cv2.imread(pic)
# Получаем значение конкретного пикселя на изображении
px = image[100, 100]
print(px)

# Изменим значение конкретного пикселя
image[100, 100] = [255, 255, 255]
print(image[100, 100])

[206 118  42]
[255 255 255]


Здесь представлен код для доступа к конкретному каналу пикселя и его изменение методами библиотеки numpy:

In [2]:
# Получаем доступ к красному каналу для конкретного пикселя на изображении
image.item(10, 10, 2)

28

In [3]:
# Изменяем значение для красного канала
image.itemset((10, 10, 2), 100)
image.item(10, 10, 2)

100

# Свойства изображения
Для получения свойств изображения, таких как размер, количество пикселей и тип значений можно использовать нижеперечисленные методы:

In [4]:
# Получаем размер изображения
print(image.shape)

# Общее количество пикселей на изображении
print(image.size)

# Тип данных изображения
print(image.dtype)

(2160, 3840, 3)
24883200
uint8


# ROI - Опорные области изображения
Для повышения точности и производительности алгоритма также можно использовать часть изображения:

In [5]:
# Выбор и копирование региона изображения
img = image[280:340, 330:390]
image[273:333, 100:160] = img

cv2.imshow('image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Разделение на цветовые плоскости
На изображении можно получить доступ к отдельным каналам и использовать это для изменения изображения. Несколько вариантов разделения на цветовые пространства показаны ниже:

In [6]:
# Разделение на каналы
b, g, r = cv2.split(image)
# Изменение порядка каналов для другого пространства
image2 = cv2.merge((r, g, b))

cv2.imshow('image', image)
cv2.imshow('image2', image2)

# Другой вариант разделения и вывода изображения в зеленых тонах
image2[:,:,2] = 0
image2[:,:,0] = 0

bb = image2[:, :, 0]
gg = image2[:, :, 1]
rr = image2[:, :, 2]

image3 = cv2.merge((rr, gg, bb))

cv2.imshow('image3', image3)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Арифметические операции над изображениями
## Сложение изображений
Для сложения изображений с использованием OpenCV можно использовать метод add(). Аргументы метода:
* src1: объект первого изображения для суммирования;
* src2: объект второго изображения для суммирования;
* dst: целевое выходное изображение;
* mask: маска для наложения на изображение;
* dtype: тип данных изображения.

Сложение с помощью numpy выглядит как стандартная арифметическая операция. Разница в том, что сложение OpenCV выполняется с насыщением, а в numpy - по модулю.

Реализация обоих подходов продемонстрирована ниже:

In [7]:
import numpy as np


# Сложение двух изображений с использованием opencv и numpy
x, y = np.uint8([250]), np.uint8([10])
print(cv2.add(x, y))
print(x + y)

# Пример на реальных изображениях
image4 = cv2.add(image, image, image)
cv2.imshow('image4', image4)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[260.]
 [  0.]
 [  0.]
 [  0.]]
[4]


# Битовые операции
В примере ниже используются операции NOT и AND, которые в OpenCV представлены методами bitwise_not() и bitwise_and(). Кроме того, для пороговой обработки изображения применяется метод threshold().

Для bitwise_not() предусмотрены следующие аргументы:
* src: исходное изображение для обработки;
* dst: результирующее изображение;
* mask: маска, накладываемая на изображение.

Для bitwise_and() доступны следующие аргументы:
* src1: первое исходное изображение для обработки;
* src2: второе исходное изображение для обработки;
* dst: результирующее изображение;
* mask: маска, накладываемая на изображение.

Для метода threshold() предусмотрены следующие аргументы:
* src: объект изображения;
* thresh: порог, выше и ниже которого значения пикселей будут изменяться;
* maxval: максимальное значение для пикселя;
* type: тип применяемой обработки;
* dst: результирующий объект изображения.

In [8]:
image = cv2.imread(pic)
logo = cv2.imread("../resources/logo.png", 1)

# Создаем ROI
rows, cols, channels = logo.shape
roi = image[0:rows, 0:cols]

# Создаем маску логотипа и его инверсную маску
img2gray = cv2.cvtColor(logo, cv2.COLOR_BGR2GRAY)
ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)

mask_inv = cv2.bitwise_not(mask)

# Затемняем область логотипа в ROI
img1_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

# Берем только область логотипа из изображения логотипа.
img2_fg = cv2.bitwise_and(logo, logo, mask=mask)

# Помещаем логотип в ROI и изменяем основное изображение
dst = cv2.add(img1_bg, img2_fg)
image[0:rows, 0:cols] = dst

cv2.imshow('result', image)
cv2.imshow('inv', mask_inv)
cv2.imshow('bg', img1_bg)
cv2.imshow('fg', img2_fg)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Смешивание изображений
Для смешивания изображений используется метод addWeighted(). Метод идиентичен методу для сложения изображений, но включает в себя параметры весов для смешивания. Аргументы, которые предусмотрены для метода:
* src1: первый исходный объект изображения;
* alpha: значение веса для альфа-канала;
* src2: второй исходный объект изображения;
* beta: значение веса для бета-канала;
* gamma: значение веса для гамма-канала;
* dst: объект выходного изображения;
* dtype: тип данных выходного изображения.

Пример смешивания изображений реализован ниже.

In [9]:
img1 = cv2.imread(pic)
logo.resize(2160, 3840, 3)
# Смешивание изображений с эффектом прозрачности
dst = cv2.addWeighted(img1, 0.7, logo, 0.3, 0)

cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()